In [1]:
import torch


# **Primeiros passos com tensores**

### Criação de tensores

##### - De listas para Tensores


In [5]:
# Criar tensores a partir de listas
lista = [[1,2,3],
         [4,5, 6]]

tns = torch.Tensor(lista)
print(tns.dtype)
print(tns) # De padrão vem float

tns2 = torch.LongTensor(lista)
print(tns2.dtype)
print(tns2) # Agora vem inteiro

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


##### - De arrays para tensores

In [9]:
# Criar tensores a partir de array numpy
import numpy as np
arr = np.random.rand(3,4) #3 linhas por 4 colunas
print(arr)

tns = torch.from_numpy(arr)
print(tns) #Preserva o tipo do array

[[0.95196815 0.53538417 0.5589488  0.83859785]
 [0.33024993 0.768155   0.2244034  0.74036518]
 [0.37864367 0.09955037 0.49855658 0.56393859]]
tensor([[0.9520, 0.5354, 0.5589, 0.8386],
        [0.3302, 0.7682, 0.2244, 0.7404],
        [0.3786, 0.0996, 0.4986, 0.5639]], dtype=torch.float64)


##### - Inicialização de tensores do zero

In [11]:
#Já iniciar como tensor
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3) #Distribuição normal aleatoria

print(tns1)
print(tns0)
print(tnsr)


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 1.4611,  0.3007,  1.4895],
        [-0.4869, -0.4860,  0.4485],
        [ 0.5720,  1.6113,  0.1526]])


##### - De tensores para array

In [14]:
print(tnsr)
print(tnsr.dtype)
arr = tnsr.data.numpy()
print(arr)
print(arr.dtype)

tensor([[ 1.4611,  0.3007,  1.4895],
        [-0.4869, -0.4860,  0.4485],
        [ 0.5720,  1.6113,  0.1526]])
torch.float32
[[ 1.4610807   0.30066228  1.4894835 ]
 [-0.486884   -0.4859584   0.44845453]
 [ 0.5720443   1.6112838   0.15264508]]
float32


### Indexação (Acessar um valor especifico)

##### - Substituição

In [15]:
print(tnsr)
tnsr[0,2] = 100
print(tnsr)

tensor([[ 1.4611,  0.3007,  1.4895],
        [-0.4869, -0.4860,  0.4485],
        [ 0.5720,  1.6113,  0.1526]])
tensor([[  1.4611,   0.3007, 100.0000],
        [ -0.4869,  -0.4860,   0.4485],
        [  0.5720,   1.6113,   0.1526]])


##### - Pegar valores especificos

In [19]:
print(tnsr)

print("")
print(tnsr[:2]) #Pegar as duas primeiras linhas
print("")
print(tnsr[:2, 2]) #Pegar a terceira coluna das duas primeiras linhas

tensor([[  1.4611,   0.3007, 100.0000],
        [ -0.4869,  -0.4860,   0.4485],
        [  0.5720,   1.6113,   0.1526]])

tensor([[  1.4611,   0.3007, 100.0000],
        [ -0.4869,  -0.4860,   0.4485]])

tensor([100.0000,   0.4485])


### Operações com tensores

In [25]:
tns_soma = torch.randint(low=0, high=10, size=(3, 3))
print(tns_soma)
print("")
tns_soma2 = torch.randint(low=0, high=10, size=(3, 3))
print(tns_soma2)
print("")
tns_soma3 = tns_soma + tns_soma2 #é preciso ter as mesmas dimensões
print(tns_soma3)


tensor([[5, 2, 6],
        [4, 8, 6],
        [5, 2, 8]])

tensor([[7, 7, 4],
        [9, 0, 0],
        [7, 2, 8]])

tensor([[12,  9, 10],
        [13,  8,  6],
        [12,  4, 16]])


### Função Size() e View()

In [26]:
print(tnsr.size())

torch.Size([3, 3])


In [32]:
# 2 linhas, 3 colunas, 2 de profundidade (cubo)
tns = torch.randn(2, 2, 3)
print(tns)
print("")
#Isso resultado em um tensor com 12 elementos

tns_achatado = tns.view(12) # Achatamos em uma unica linha e coluna
print(tns_achatado)
print("")
tns_achatado = tns.view(2, 6) # Achatamos em duas linhas e 6 colunas
print(tns_achatado)
print("")



tensor([[[-0.2831,  0.2351, -0.1368],
         [ 0.6100,  0.4441,  0.8425]],

        [[ 0.1665,  0.4147, -2.0195],
         [-0.8562, -0.0324, -1.5172]]])

tensor([-0.2831,  0.2351, -0.1368,  0.6100,  0.4441,  0.8425,  0.1665,  0.4147,
        -2.0195, -0.8562, -0.0324, -1.5172])

tensor([[-0.2831,  0.2351, -0.1368,  0.6100,  0.4441,  0.8425],
        [ 0.1665,  0.4147, -2.0195, -0.8562, -0.0324, -1.5172]])

